name: 'Updating Stargazed'
on:
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      - name: 'Use GitHub Actions'
        uses: actions/checkout@v2
      - name: 'Use Node.js 12.x'
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'Install Package'
        run: 'npm install --global stargazed'
      - name: 'Update Repo'
        env:
          NADS: '${{ secrets.NADS }}'
        run: 'stargazed --username  "abhisheknaiidu" --token ${NADS} --repo "nads" --message "stargazed update by GitHub Actions Workflow" -s -w'
